CREATE TABLE `MEMBER` (
  `MEM_NO` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `MEM_ID` VARCHAR(100) NOT NULL,
  `MEM_PW` VARCHAR(100) NOT NULL,
  `MEM_NAME` VARCHAR(100) NOT NULL,
  `MEM_BIRTHDAY` DATE NOT NULL,
  `MEM_PHONE` VARCHAR(100) NOT NULL,
  `MEM_EMAIL` VARCHAR(200) NOT NULL,
  `MEM_GENDER` INT NOT NULL,
  `MEM_BESTREVIEW` INT NOT NULL DEFAULT 0,
  `MEM_PROFILEIMAGE` VARCHAR(200),
  `MEM_JOINDATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MEM_LAST_LOGIN` DATETIME,
  `MEM_JOINWAY` VARCHAR(100) NOT NULL DEFAULT 'D',
  `MEM_ISMASTER` INT NOT NULL DEFAULT 0
);

CREATE TABLE `BOARD` (
  `MEM_NO` BIGINT NOT NULL,
  `B_NO` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `B_TITLE` VARCHAR(100) NOT NULL,
  `B_CONTENT` VARCHAR(1000) NOT NULL,
  `B_THUMBNAIL` VARCHAR(1000),
  `B_VIEW` BIGINT DEFAULT 0,
  `B_LIKE` BIGINT DEFAULT 0,
  `B_CREATETIME` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `B_COMMENTCOUNT` INT DEFAULT 0,
  `B_IS_ADMIN` INT DEFAULT 0,
  `B_SECRET` INT DEFAULT 0
);

CREATE TABLE `COMMENT` (
  `MEM_NO` BIGINT NOT NULL,
  `B_NO` BIGINT NOT NULL,
  `C_NO` INT PRIMARY KEY AUTO_INCREMENT,
  `C_CONTENT` VARCHAR(1000) NOT NULL,
  `C_CREATETIME` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `TRAVEL` (
  `T_CONTENTNO` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `T_SIDO` VARCHAR(100),
  `T_SIGUNGU` VARCHAR(100),
  `T_CONTENTTYPEID` INT,
  `T_CONTENTID` VARCHAR(100),
  `T_CONTENTNAME` VARCHAR(100),
  `T_MAIN_IMAGE` VARCHAR(1000),
  `T_THUMB_IMAGE` VARCHAR(1000),
  `T_MAPX` VARCHAR(20),
  `T_MAPY` VARCHAR(20),
  `T_CAT1` VARCHAR(10),
  `T_CAT2` VARCHAR(10),
  `T_CAT3` VARCHAR(20)
);

CREATE TABLE `FESTIVAL` (
  `T_CONTENTNO` BIGINT NOT NULL,
  `F_NO` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `F_STARTDATE` DATE,
  `F_ENDDATE` DATE,
  `F_CONTENT` VARCHAR(1000),
  `F_PRICE` VARCHAR(100),
  `F_OPENTIME` VARCHAR(100)
);

CREATE TABLE `DETAIL` (
  `T_CONTENTNO` BIGINT NOT NULL,
  `D_NO` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `D_ADDRESS` VARCHAR(100),
  `D_PHONE` VARCHAR(100),
  `D_URL` VARCHAR(1000),
  `D_VIEW` BIGINT,
  `D_LIKE` BIGINT,
  `D_INFORMATION` VARCHAR(1000)
);

CREATE TABLE `ADDITIONAL` (
  `T_CONTENTNO` BIGINT NOT NULL,
  `A_NO` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `A_PET` INT,
  `A_HOLIDAY` VARCHAR(100),
  `A_PRICE` VARCHAR(100),
  `A_PARK` INT,
  `A_WHEEL` INT,
  `A_STOLLER` INT,
  `A_BLIND` INT
);

CREATE TABLE `USER_CALENDER` (
  `MEM_NO` BIGINT NOT NULL,
  `T_CONTENTNO` BIGINT NOT NULL,
  `CAL_NO` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `CAL_COLER` VARCHAR(100),
  `CAL_TITLE` VARCHAR(100) NOT NULL,
  `CAL_STARTDATE` DATE NOT NULL,
  `CAL_ENDDATE` DATE NOT NULL,
  `CAL_MEMO` VARCHAR(100),
  `CAL_BOARDNO` INT
);

CREATE TABLE `NOTICE` (
  `MEM_NO` BIGINT NOT NULL,
  `N_NO` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `N_SUBJECT` VARCHAR(100),
  `N_CONTENT` VARCHAR(1000),
  `N_WRITER` VARCHAR(20),
  `N_CREATETIME` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `QNA` (
  `MEM_NO` BIGINT NOT NULL,
  `Q_NO` INT PRIMARY KEY AUTO_INCREMENT,
  `Q_ISANSWERED` INT DEFAULT 0,
  `Q_SUBJECT` VARCHAR(20),
  `Q_CONTENT` VARCHAR(200),
  `Q_CREATETIME` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `FAQ` (
  `MEM_NO` BIGINT NOT NULL,
  `FAP_NO` INT PRIMARY KEY AUTO_INCREMENT,
  `FAQ_SUBJECT` VARCHAR(100),
  `FAQ_CONTENT` VARCHAR(1000),
  `FAQ_CREATETIME` DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE `MEMBER` ADD FOREIGN KEY (`MEM_NO`) REFERENCES `BOARD` (`MEM_NO`);

ALTER TABLE `BOARD` ADD FOREIGN KEY (`B_NO`) REFERENCES `COMMENT` (`B_NO`);

ALTER TABLE `MEMBER` ADD FOREIGN KEY (`MEM_NO`) REFERENCES `COMMENT` (`MEM_NO`);

ALTER TABLE `TRAVEL` ADD FOREIGN KEY (`T_CONTENTNO`) REFERENCES `FESTIVAL` (`T_CONTENTNO`);

ALTER TABLE `TRAVEL` ADD FOREIGN KEY (`T_CONTENTNO`) REFERENCES `DETAIL` (`T_CONTENTNO`);

ALTER TABLE `TRAVEL` ADD FOREIGN KEY (`T_CONTENTNO`) REFERENCES `ADDITIONAL` (`T_CONTENTNO`);

ALTER TABLE `MEMBER` ADD FOREIGN KEY (`MEM_NO`) REFERENCES `USER_CALENDER` (`MEM_NO`);

ALTER TABLE `TRAVEL` ADD FOREIGN KEY (`T_CONTENTNO`) REFERENCES `USER_CALENDER` (`T_CONTENTNO`);

ALTER TABLE `MEMBER` ADD FOREIGN KEY (`MEM_NO`) REFERENCES `NOTICE` (`MEM_NO`);

ALTER TABLE `MEMBER` ADD FOREIGN KEY (`MEM_NO`) REFERENCES `QNA` (`MEM_NO`);

ALTER TABLE `MEMBER` ADD FOREIGN KEY (`MEM_NO`) REFERENCES `FAQ` (`MEM_NO`);
