-- MEMBER 테이블
CREATE TABLE MEMBER (
    MEM_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    MEM_ID VARCHAR(100) NOT NULL,
    MEM_PW VARCHAR(100) NOT NULL,
    MEM_NAME VARCHAR(100) NOT NULL,
    MEM_BIRTHDAY DATE NOT NULL,
    MEM_PHONE VARCHAR(100) NOT NULL,
    MEM_EMAIL VARCHAR(200) NOT NULL,
    MEM_GENDER INT NOT NULL CHECK (MEM_GENDER IN (0, 1)),
    MEM_BESTREVIEW INT NOT NULL DEFAULT 0 CHECK (MEM_BESTREVIEW IN (0, 1)),
    MEM_PROFILEIMAGE VARCHAR(200),
    MEM_JOINDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MEM_LAST_LOGIN DATETIME,
    MEM_JOINWAY VARCHAR(100) NOT NULL DEFAULT 'D' CHECK (MEM_JOINWAY IN ('D', 'N', 'K', 'G')),
    MEM_ISMASTER INT NOT NULL DEFAULT 0 CHECK (MEM_ISMASTER IN (0, 1))
);

-- BOARD 테이블
CREATE TABLE BOARD (
    MEM_NO BIGINT NOT NULL,
    B_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    B_TITLE VARCHAR(100) NOT NULL,
    B_CONTENT VARCHAR(1000) NOT NULL,
    B_THUMBNAIL VARCHAR(1000),
    B_VIEW BIGINT DEFAULT 0,
    B_LIKE BIGINT DEFAULT 0,
    B_CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    B_COMMENTCOUNT INT DEFAULT 0,
    B_IS_ADMIN INT DEFAULT 0 CHECK (B_IS_ADMIN IN (0, 1)),
    B_SECRET INT DEFAULT 0 CHECK (B_SECRET IN (0, 1)),
    FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO)
);

-- COMMENT 테이블
CREATE TABLE COMMENT (
    B_NO BIGINT NOT NULL,
    MEM_NO BIGINT NOT NULL,
    C_NO INT AUTO_INCREMENT PRIMARY KEY,
    C_CONTENT VARCHAR(1000) NOT NULL,
    C_CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (B_NO) REFERENCES BOARD(B_NO),
    FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO)
);

-- TRAVEL 테이블
CREATE TABLE TRAVEL (
    T_CONTENTNO BIGINT AUTO_INCREMENT PRIMARY KEY,
    T_SIDO VARCHAR(100),
    T_SIGUNGU VARCHAR(100),
    T_CONTENTTYPEID INT,
    T_CONTENTID VARCHAR(100),
    T_CONTENTNAME VARCHAR(100),
    T_MAIN_IMAGE VARCHAR(1000),
    T_THUMB_IMAGE VARCHAR(1000),
    T_MAPX VARCHAR(20),
    T_MAPY VARCHAR(20),
    T_CAT1 VARCHAR(10),
    T_CAT2 VARCHAR(10),
    T_CAT3 VARCHAR(20)
);

-- FESTIVAL 테이블
CREATE TABLE FESTIVAL (
    T_CONTENTNO BIGINT NOT NULL,
    F_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    F_STARTDATE DATE,
    F_ENDDATE DATE,
    F_CONTENT VARCHAR(1000),
    F_PRICE VARCHAR(100),
    F_OPENTIME VARCHAR(100),
    FOREIGN KEY (T_CONTENTNO) REFERENCES TRAVEL(T_CONTENTNO)
);

-- DETAIL 테이블
CREATE TABLE DETAIL (
    T_CONTENTNO BIGINT NOT NULL,
    D_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    D_ADDRESS VARCHAR(100),
    D_PHONE VARCHAR(100),
    D_URL VARCHAR(1000), -- 데이터 타입을 VARCHAR로 수정
    D_VIEW BIGINT,
    D_LIKE BIGINT,
    D_INFORMATION VARCHAR(1000),
    FOREIGN KEY (T_CONTENTNO) REFERENCES TRAVEL(T_CONTENTNO)
);

-- ADDITIONAL 테이블
CREATE TABLE ADDITIONAL (
    T_CONTENTNO BIGINT NOT NULL,
    A_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    A_PET INT CHECK (A_PET IN (0, 1)),
    A_HOLIDAY VARCHAR(100),
    A_PRICE VARCHAR(100),
    A_PARK INT CHECK (A_PARK IN (0, 1)),
    A_WHEEL INT CHECK (A_WHEEL IN (0, 1)),
    A_STOLLER INT CHECK (A_STOLLER IN (0, 1)),
    A_BLIND INT CHECK (A_BLIND IN (0, 1)),
    FOREIGN KEY (T_CONTENTNO) REFERENCES TRAVEL(T_CONTENTNO)
);

-- USER_CALENDER 테이블
CREATE TABLE USER_CALENDER (
    MEM_NO BIGINT NOT NULL,
    T_CONTENTNO BIGINT NOT NULL,
    CAL_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    CAL_COLER VARCHAR(100),
    CAL_TITLE VARCHAR(100) NOT NULL,
    CAL_STARTDATE DATE NOT NULL,
    CAL_ENDDATE DATE NOT NULL,
    CAL_MEMO VARCHAR(100),
    CAL_BOARDNO INT,
    FOREIGN KEY (MEM_NO) REFERENCES USERS(MEM_NO),
    FOREIGN KEY (T_CONTENTNO) REFERENCES CONTENT(T_CONTENTNO)
);

-- NOTICE 테이블
CREATE TABLE NOTICE (
    MEM_NO BIGINT NOT NULL,
    N_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    N_SUBJECT VARCHAR(100),
    N_CONTENT VARCHAR(1000),
    N_WRITER VARCHAR(20),
    N_CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MEM_NO) REFERENCES USERS(MEM_NO)
);

-- QNA 테이블
CREATE TABLE QNA (
    MEM_NO BIGINT NOT NULL,
    Q_NO INT AUTO_INCREMENT PRIMARY KEY,
    Q_ISANSWERED INT DEFAULT 0,
    Q_SUBJECT VARCHAR(20),
    Q_CONTENT VARCHAR(200),
    Q_CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MEM_NO) REFERENCES USERS(MEM_NO)
);

-- FAQ 테이블
CREATE TABLE FAQ (
    MEM_NO BIGINT NOT NULL,
    FAP_NO INT AUTO_INCREMENT PRIMARY KEY,
    FAQ_SUBJECT VARCHAR(100),
    FAQ_CONTENT VARCHAR(1000),
    FAQ_CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MEM_NO) REFERENCES USERS(MEM_NO)
);